version: "3.1"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/opt/bot/.env:ro
      - ./log.txt:/opt/bot/log.txt
    command: npm run start
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: /run.sh --maxmemory 100mb
    expose:
      - 6379